### ISSUE TITLE
Not pre-commit ready

### ISSUE THREAD

**Issue by janosh** [streetsidesoftware/cspell-cli#47]
I think the description on this repo ("cspell command line that can be used with pre-commit") might not match its current state.

To be used with pre-commit, it would need a [`.pre-commit-hooks.yaml`](https://github.com/streetsidesoftware/cspell/blob/main/.pre-commit-hooks.yaml) similar to https://github.com/streetsidesoftware/cspell.

I followed the discussion in https://github.com/streetsidesoftware/cspell/issues/53 but am still confused about the recommended approach. Does this repo still serve a purpose?

Related: https://github.com/streetsidesoftware/vscode-spell-checker/issues/1294

**Comment by Jason3S** [comment]
This is the right repo. I just didn't realize there was a `.pre-commit-hooks.yaml` file necessary. I'll add it.

**Comment by Jason3S** [comment]
I have added the file. Please try it out.

**Comment by janosh** [comment]
Cool, all working now! Thanks for the quick help.

How do I pass a dictionary of custom words to this hook? I tried passing the name and the path of my dictionary to `cspell-cli help link add` but nothing happened, I think.

```sh
cspell-cli help
```

> Usage: cspell [options] [command]
> 
> Spelling Checker for Code
> 
> Options:
>   -V, --version               output the version number
>   --no-color                  Turn off color.
>   --color                     Force color
>   -h, --help                  display help for command
> 
> Commands:
>   lint [options] [files...]   Check spelling
>   trace [options] <words...>  Trace words
>     Search for words in the configuration and dictionaries.
>   check [options] <files...>  Spell check file(s) and display the result. The full file is displayed in color.
>   link                        Link dictionaries any other settings to the cspell global config.
>   help [command]              display help for command

**Comment by Jason3S** [comment]
The best thing is to add `cspell.json` file.

If the `cspell.json` file is in the folder structure, cspell will find it.

Looks like pre-commit allows passing `args` to the command line. Passing the `-c <path to file>/cspell.json` should help.

**Comment by Jason3S** [comment]
`link` works with dictionary packages.

It will add a packaged dictionary to your global settings.
Example: [cspell-dicts/dictionaries/nl_NL](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/nl_NL#installation)

**Comment by janosh** [comment]
I see. Is there a way to pass the path to a dictionary file to `cspell-cli` directly via `args`?

**Comment by Jason3S** [comment]
The best thing is to create a `cspell.json` file:

In VS Code, if you right click on a work the spell checker doesn't know, it gives you the option to create a config file.
![image](https://user-images.githubusercontent.com/3740137/133064629-e17cd34b-f9bb-4a41-af14-ba82a7d35951.png)

It will create a file that looks like this:

```json
{
    "version": "0.2",
    "ignorePaths": [],
    "dictionaryDefinitions": [],
    "dictionaries": [],
    "words": [],
    "ignoreWords": [],
    "import": []
}
```

It will also create a custom dictionary for you:
![image](https://user-images.githubusercontent.com/3740137/133065157-8a864fb5-1c15-48d0-8937-c40cff2af26c.png)

It will update the `cspell.json` for you:

```json
{
    "version": "0.2",
    "ignorePaths": [],
    "dictionaryDefinitions": [
        {
            "name": "custom-dictionary",
            "path": "./.cspell/custom-dictionary.txt",
            "addWords": true
        }
    ],
    "dictionaries": [
        "custom-dictionary"
    ],
    "words": [],
    "ignoreWords": [],
    "import": []
}
```

**Comment by janosh** [comment]
Doesn't show up for me on right click, but is available from the VS Code command palette.

![Screen Shot 2021-09-13 at 11 14 42](https://user-images.githubusercontent.com/30958850/133067495-2fef28b7-4a65-43a0-8d8e-7c0d6bae02ef.png)

Good to know `cspell` supports both JSON and Yaml config files. I prefer Yaml for readability.

![Screen Shot 2021-09-13 at 11 21 29](https://user-images.githubusercontent.com/30958850/133067858-ac6ec1fb-6e62-4634-8100-e1c13315b597.png)


Looks like this is sufficient:

```yaml
# cspell.config.yaml
dictionaryDefinitions:
  - name: myWords
    path: path/to/cSpell_dict.txt
    addWords: true
dictionaries:
  - myWords
```

Is JSON recommended over Yaml? Why the extra `.config` in the Yaml file name?

**Comment by Jason3S** [comment]
> Is JSON recommended over Yaml? 

VS Code supports JSON better than Yaml. It will check the file to make sure it matches the schema. It does not do that for Yaml files.

> Why the extra .config in the Yaml file name?

The extra `.config` makes it explicit that it is a config file and not an action file. It seems to be the convention with the other command line linters to use the `.config`.

**Comment by janosh** [comment]
> VS Code supports JSON better than Yaml. It will check the file to make sure it matches the schema. It does not do that for Yaml files.

I see. In that case, I'll add both formats to #50.
