### ISSUE TITLE
Don't Error When No Files to Check as Pre-commit Hook

### ISSUE THREAD

**Issue by Kurt-von-Laven** [streetsidesoftware/cspell-cli#52]
I can see the value in exiting with an error code in general when cspell is exclusively passed excluded files, but this is a problematic default in the context of a pre-commit hook since any given commit may rightly only modify excluded files.

**Comment by Jason3S** [comment]
How about trying add `--no-must-find-files` to the args?

To see the other options: `cspell-cli lint -h`

**Comment by Kurt-von-Laven** [comment]
Yep, that fixes it; thank you. (I was looking at the [wrong](https://github.com/streetsidesoftware/cspell-cli) [docs](https://streetsidesoftware.github.io/cspell/configuration/).) Would you accept a pull request to add this argument as a default for the pre-commit hook?

**Comment by Jason3S** [comment]
A pull request to update the README would be wonderful. Plus a bit out how to get Help with the command line options.

**Comment by Jason3S** [comment]
I'm not sure how to change the default arguments from `cspell-cli`, it doesn't have any real code.

**Comment by Kurt-von-Laven** [comment]
I opened a pull request to add the argument as a default for the pre-commit hook and a follow-up issue to remind myself to update the README.
