### ISSUE TITLE
Use CSpell option `--file-list` in pre-commit hook

### ISSUE THREAD

**Issue by Jason3S** [streetsidesoftware/cspell-cli#90]
CSpell now supports an option `--file-list` to give it a file that contains a list of files to be checked.

This is necessary for handling large diffs with 1000's of files. The command line buffer isn't large enough.

For example to spell check repo changes:

```sh
git diff --name-only | npx cspell --file-list stdin
```

**Comment by Jason3S** [comment]
@Kurt-von-Laven,

Do you know the best way to do this? I don't use pre-commit in my projects.

**Comment by Jason3S** [comment]
This might be a non-issue since pre-commit seems to have logic to limit the length of the command line.

**Comment by Kurt-von-Laven** [comment]
That sounds right to me, yep; pre-commit generally takes these types of things into consideration.
